const List<String> currenciesList = [
  'AUD',
  'BRL',
  'CAD',
  'CNY',
  'EUR',
  'GBP',
  'HKD',
  'IDR',
  'ILS',
  'INR',
  'JPY',
  'MXN',
  'NOK',
  'NZD',
  'PLN',
  'RON',
  'RUB',
  'SEK',
  'SGD',
  'USD',
  'ZAR'
];

const Map<String, String> cc = {
  'Australia': 'AUD',
  'Brazil': 'BRL',
  'Canada': 'CAD',
  'China': 'CNY',
  'Germany': 'EUR',
  'Britain(UK)': 'GBP',
  'Hong Kong': 'HKD',
  'Indonesia': 'IDR',
  'Israel': 'ILS',
  'India': 'INR',
  'Japan': 'JPY',
  'Mexico': 'MXN',
  'Norway': 'NOK',
  'New Zealand': 'NZD',
  'Poland': 'PLN',
  'Roman': 'RON',
  'Russia': 'RUB',
  'Sweden': 'SEK',
  'Singapore': 'SGD',
  'America(US)': 'USD',
  'South African': 'ZAR',
};

const List<String> countryList = [
  'Australia',
  'Brazil',
  'Canada',
  'China',
  'Germany',
  'Britain(UK)',
  'Hong Kong',
  'Indonesia',
  'Israel',
  'India',
  'Japan',
  'Mexico',
  'Norway',
  'New Zealand',
  'Poland',
  'Roman',
  'Russia',
  'Sweden',
  'Singapore',
  'America(US)',
  'South African'
];
